[package]
name = "rargz"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0"
clap = { version = "4.5", features = ["derive"] }
crossbeam-channel = "0.5"
num_cpus = "1.16"
rayon = "1.10"
tar = "0.4"
walkdir = "2.5"
zstd = { version = "0.13", features = ["zstdmt"] }
